"""add_car_colour_and_national_id_photo

Revision ID: 3ff1a1478578
Revises: bd1ea0650536
Create Date: 2026-04-04 16:36:01.948052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff1a1478578'
down_revision: Union[str, Sequence[str], None] = 'bd1ea0650536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
