"""add_profile_photo_url

Revision ID: 43f569adb4f4
Revises: d5e6f7g8h9i0
Create Date: 2026-05-09 18:37:18.952814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43f569adb4f4'
down_revision: Union[str, Sequence[str], None] = 'd5e6f7g8h9i0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('driver_details_license_plate_key'), 'driver_details', type_='unique')
    op.drop_column('driver_details', 'car_colour')
    op.drop_column('driver_details', 'year')
    op.drop_column('driver_details', 'license_plate')
    op.drop_column('driver_details', 'car_model')
    op.drop_column('driver_details', 'car_make')
    op.add_column('user_profiles', sa.Column('profile_photo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'profile_photo_url')
    op.add_column('driver_details', sa.Column('car_make', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('driver_details', sa.Column('car_model', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('driver_details', sa.Column('license_plate', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('driver_details', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('driver_details', sa.Column('car_colour', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('driver_details_license_plate_key'), 'driver_details', ['license_plate'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
