"""add_car_colour_and_national_id_photo

Revision ID: 46d3fa506d9c
Revises: 83e89a5c7e8c
Create Date: 2026-04-04 15:15:22.829859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46d3fa506d9c'
down_revision: Union[str, Sequence[str], None] = '83e89a5c7e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_details', sa.Column('car_colour', sa.String(), nullable=False))
    op.add_column('driver_details', sa.Column('national_id_photo_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver_details', 'national_id_photo_url')
    op.drop_column('driver_details', 'car_colour')
    # ### end Alembic commands ###
