"""add_car_colour_and_national_id_photo

Revision ID: bd1ea0650536
Revises: 46d3fa506d9c
Create Date: 2026-04-04 16:33:46.153371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd1ea0650536'
down_revision: Union[str, Sequence[str], None] = '46d3fa506d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('driver_details', 'car_colour',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('driver_details', 'national_id_photo_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('driver_details', 'national_id_photo_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('driver_details', 'car_colour',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
