"""drop_is_available_now

Revision ID: f6d78216210b
Revises: 3ff1a1478578
Create Date: 2026-04-04 18:08:12.092170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6d78216210b'
down_revision: Union[str, Sequence[str], None] = '3ff1a1478578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('driver_details', 'car_colour',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('driver_details', 'national_id_photo_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('driver_details', 'is_available_now')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_details', sa.Column('is_available_now', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('driver_details', 'national_id_photo_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('driver_details', 'car_colour',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
