"""update ride ratings schema for mutual ratings

Revision ID: b59d93e408e9
Revises: a1b2c3d4e5f6
Create Date: 2026-05-10 19:17:30.484645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b59d93e408e9'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride_ratings', sa.Column('rated_by_id', sa.String(), nullable=False))
    op.add_column('ride_ratings', sa.Column('rated_by_role', sa.String(), nullable=False))
    op.add_column('ride_ratings', sa.Column('rated_user_id', sa.String(), nullable=False))
    op.drop_index(op.f('ix_ride_ratings_ride_id'), table_name='ride_ratings')
    op.create_index(op.f('ix_ride_ratings_ride_id'), 'ride_ratings', ['ride_id'], unique=False)
    op.drop_column('ride_ratings', 'driver_id')
    op.drop_column('ride_ratings', 'rider_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride_ratings', sa.Column('rider_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('ride_ratings', sa.Column('driver_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_ride_ratings_ride_id'), table_name='ride_ratings')
    op.create_index(op.f('ix_ride_ratings_ride_id'), 'ride_ratings', ['ride_id'], unique=True)
    op.drop_column('ride_ratings', 'rated_user_id')
    op.drop_column('ride_ratings', 'rated_by_role')
    op.drop_column('ride_ratings', 'rated_by_id')
    # ### end Alembic commands ###
